// <auto-generated />
using CV_3._1.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CV_3._1.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CV_3._1.Models.Admin", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("KullaniciAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Parola")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("admins");
                });

            modelBuilder.Entity("CV_3._1.Models.PanelAbout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NelerYapıyorumAd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NelerYapıyorumIcerik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tanıtım")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("panelAbouts");
                });

            modelBuilder.Entity("CV_3._1.Models.PanelEducation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("OkulAd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OkulAlan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OkulIcerik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OkulYıl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("panelEducations");
                });

            modelBuilder.Entity("CV_3._1.Models.PanelExperiance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DeneyimAd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeneyimAlan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeneyimIcerik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeneyimYıl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("panelExperiances");
                });

            modelBuilder.Entity("CV_3._1.Models.PanelProfil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Github")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Instagram")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Konum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KonumAdresi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Linkedin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MeslekAlanı")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfilResmi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Twitter")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("panelProfils");
                });

            modelBuilder.Entity("CV_3._1.Models.PanelProject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ProjectAd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectAdres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectIcerik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectResim")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("panelProjects");
                });
#pragma warning restore 612, 618
        }
    }
}
